urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import TemplateView

# It uses LOGIN_URL from settings.py
# from django.contrib.auth.decorators import login_required

from website import ajax, views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(
        r'^home_filter/(?P<content_type>\w+)/(?P<cc_id>-?\d+)/$',
        views.Home.as_view(), name='home_filter'
    ),

    url(
        r'^person/(?P<person_id>\d+)/$', views.ContentsByPerson.as_view(),
        name='contents_by_person'
    ),
    url(
        r'^person/(?P<content_type>\w+)/(?P<cc_id>-?\d+)/(?P<person_id>\d+)'
        + '/(?P<my_contents>\w+)/$', views.ContentsByPerson.as_view(),
        name='contents_by_person'
    ),
    url(
        r'^my_profile/(?P<user_id>\d+)/$',
        views.ContentsByPerson.as_view(), name='my_profile'
    ),


    url(
        r'^search_contents/$', views.SearchResultsContents.as_view(),
        name='search_results_contents'
    ),

    url(
        r'^search_persons/$', views.SearchResultsPersons.as_view(),
        name='search_results_persons'
    ),

    url(r'^filter_persons/like_content/(?P<content_id>\d+)/$',
        views.FilterPersons.as_view(), name='filter_persons_like_content'),
    url(r'^filter_persons/by_category/(?P<user_category_id>\d+)/$',
        views.FilterPersons.as_view(), name='filter_persons_by_category'),
    url(r'^filter_persons/(?P<person_id>\d+)/(?P<filter>\w+)/$',
        views.FilterPersons.as_view(), name='filter_persons'),
    url(
        r'^account_add/(?P<step>\d+)/$',
        views.AccountAdd.as_view(), name="account_add"
    ),
    url(
        r'^account_update/(?P<user_id>\d+)/(?P<step>\d+)/$',
        views.AccountUpdate.as_view(), name="account_update"
    ),
    url(
        r'^account_created/$', TemplateView.as_view(
            template_name='website/account/account_created.html'
        ),
        name="account_created"
    ),

    url(
        r'^content_details/(?P<pk>\d+)/(?P<content_type>\w+)/$',
        views.ContentDetails.as_view(), name="content_details"
    ),
    # POST url
    url(
        r'^content_details/add_comment/$',
        views.add_comment_to_content, name="add_comment_to_content"
    ),
    url(
        r'^content_add/(?P<step>\d+)/(?P<content_type>\w+)/$',
        views.ContentAdd.as_view(), name="content_add"
    ),
    url(
        r'^content_update/(?P<content_id>\d+)/(?P<step>\d+)/(?P<content_type>\w+)/$',
        views.ContentUpdate.as_view(), name="content_update"
    ),
    url(
        r'^tutorial_part_display/(?P<cur_id>\d+)/(?P<direction>\w+)/$',
        views.tutorial_part_display, name="tutorial_part_display"
    ),
    url(
        r'^tutorial_part_add/(?P<prev_content_id>\d+)/$',
        views.tutorial_part_add, name="tutorial_part_add"
    ),
    url(
        r'^about_us/$', TemplateView.as_view(
            template_name='website/about_us.html'
        ),
        name="about_us"
    ),
    url(
        r'^terms_and_conditions/$', TemplateView.as_view(
            template_name='website/terms_and_conditions.html'
        ),
        name="terms_and_conditions"
    ),
    url(
        r'^privacy/$', TemplateView.as_view(
            template_name='website/privacy.html'
        ),
        name="privacy"
    ),
    url(
        r'^contacts/$', TemplateView.as_view(
            template_name='website/contacts.html'
        ),
        name="contacts"
    ),

    url(r'^account/login/$', views.Login.as_view(), name='login'),
    url(r'^account/logout/$', views.Logout.as_view(), name='logout'),

    url(
        r'^error/$', TemplateView.as_view(
            template_name='website/generic_error_page.html'
        ),
        name="generic_error_page"
    ),

    # POST URL (AJAX)
    url(
        r'^ajax/content/swap_like_it/$',
        ajax.swap_like_content, name="swap_like_content"
    ),
    url(
        r'^ajax/content/is_liked/$',
        ajax.is_content_liked, name="is_content_liked"
    ),
    # These URLs are directly used in follow_person.js
    url(r'^ajax/person/swap_follows/$', ajax.swap_follows, name="swap_follows"),
    url(
        r'^ajax/person/is_user_followed/$',
        ajax.is_user_followed, name="is_user_followed"
    ),

    url(
        r'^account/change_password/(?P<pk>\d+)/$', 
        views.ChangePassword.as_view(), name="change_password"
    ),

    url(r'^account/reset_password_request/(?P<init>\w*)', views.ResetPasswordRequest.as_view(), name="reset_password_request"),
    url(r'^account/reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ResetPasswordConfirm.as_view(),name='reset_password_confirm'),
    url(
        r'^account/reset_password_link_sent/$', TemplateView.as_view(
            template_name='website/account/reset_password_link_sent.html'
        ),
        name="reset_password_link_sent"
    ),
    url(
        r'^account/reset_password_done/$', TemplateView.as_view(
            template_name='website/account/reset_password_done.html'
        ),
        name="reset_password_done"
    ),

] + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # Only for development purposes

"""
print("media root: %s" % settings.MEDIA_ROOT)
print("media url: %s" % settings.MEDIA_URL)
print(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
"""

models.py
# -*- coding: utf-8 -*-

import os
import uuid
import logging

from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User as DjangoUser
from django_countries.fields import CountryField

import sorl  # for thumbnails

logger = logging.getLogger(__name__)


def generate_image_path(instance, filename):
    """Generate a unique file name
    """
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploads/content', filename)


class ReferenceEntity(models.Model):
    label = models.CharField(u"Label", max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.label


class UserCategory(ReferenceEntity):
    class Meta:
        verbose_name = u"Categoria utente"
        verbose_name_plural = u"Categorie utente"


class UserProfileQuerySet(models.QuerySet):
    def search(self, search_text):
        return self.filter(
            Q(user__first_name__icontains=search_text.lower()) |
            Q(user__last_name__icontains=search_text.lower()) |
            Q(city__icontains=search_text.lower()) |
            Q(category__label__icontains=search_text.lower()) |
            Q(information__icontains=search_text.lower())
        )

    def like_content(self, content_id):
        return [
            cl.user_profile
            for cl in ContentLike.objects.filter(content__id=content_id)
        ]


class UserProfile(models.Model):
    def list_contents(self):
        return Content.objects.filter(user_created_by__id=self.id)

    def list_followers(self):
        # Get all ids of users that are following
        # the current UserProfile instance
        user_following_ids = (
            UserFollow.objects
            .filter(user_followed__id=self.id)
            .values_list('user_following', flat=True)
        )
        return UserProfile.objects.filter(id__in=user_following_ids)

    def list_following(self):
        # Get all ids of users that
        # the current UserProfile instance is following
        user_followed_ids = (
            UserFollow.objects
            .filter(user_following__id=self.id)
            .values_list('user_followed', flat=True)
        )
        return UserProfile.objects.filter(id__in=user_followed_ids)

    def list_close_to_me(self):
        return (
            UserProfile.objects
            .filter(
                Q(city__iexact=self.city, country=self.country) |
                Q(place_interest_1__iexact=self.city) |
                Q(place_interest_2__iexact=self.city),
                country=self.country
            )
            .exclude(id=self.id)
        )

    def is_followed_by(self, user_profile_followed_id):
        return (
            UserFollow.objects
            .filter(
                user_following__id=user_profile_followed_id,
                user_followed__id=self.id
            )
            .exists()
        )

    def is_following(self, user_profile_to_follow_id):
        return (
            UserFollow.objects
            .filter(
                user_following__id=self.id,
                user_followed__id=user_profile_to_follow_id
            )
            .exists()
        )

    def swap_following(self, user_profile_to_follow):
        user_follow = (
            UserFollow.objects
            .filter(
                user_following__id=self.id,
                user_followed__id=user_profile_to_follow.id
            )
        )
        if user_follow:
            # Already followed => we don't follow
            user_follow.delete()
        else:
            # Follow him!
            user_follow = UserFollow()
            user_follow.user_following = self
            user_follow.user_followed = user_profile_to_follow
            user_follow.save()

    def get_avatar_path(instance, filename):
        """Generate a file name with the username
        """
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (instance.user.get_username(), ext)
        return os.path.join('uploads/avatar', filename)

    @staticmethod
    def get_by_user(user_id):
        return UserProfile.objects.get(user__id=user_id)

    user = models.OneToOneField(DjangoUser, on_delete=models.CASCADE)
    city = models.CharField(u"Città", max_length=20)
    place_interest_1 = models.CharField(
        u"Altra area di interesse (Città)",
        max_length=20, null=True, blank=True
    )
    place_interest_2 = models.CharField(
        u"Altra area di interesse (Città)", 
        max_length=20, null=True, blank=True
    )
    country = CountryField(verbose_name=u"Stato", default="IT")
    category = models.ForeignKey(UserCategory, verbose_name=u"Categoria utente")
    sex = models.CharField(
        u"Sesso", max_length=1, choices=(('m', u'Maschio'), ('f', u'Femine'))
    )
    age = models.PositiveSmallIntegerField(u"Età", null=True, blank=True)
    web_site = models.URLField(u"Sito web", blank=True, null=True)
    information = models.TextField(u"Altre informazioni", null=True, blank=True)
    avatar = sorl.thumbnail.ImageField(
        upload_to=get_avatar_path, null=True, blank=True
    )
    newsletter_registered = models.BooleanField(
        u"Registrazione newsletter", default=True
    )
    followed_users = models.ManyToManyField(
        'UserProfile', through='UserFollow',
        through_fields=('user_following', 'user_followed')
    )
    mail_post_liked = models.BooleanField(
        u"Ricevere una mail per un post 'mi piacce'", default=True
    )
    mail_followed = models.BooleanField(
        u"Ricevere una mail quando sono seguito", default=True
    )
    mail_comment = models.BooleanField(
        u"Ricevere una mail quando un contenuto è stato commentato",
        default=True
    )
    created_on = models.DateTimeField(
        verbose_name=u"Created on", auto_now_add=True
    )
    modified_on = models.DateTimeField(
        verbose_name=u"Updated on", auto_now=True, null=True, blank=True
    )

    objects = UserProfileQuerySet.as_manager()

    class Meta:
        verbose_name = u"Utente IA"
        verbose_name_plural = u"Utenti IA"

    def last_modified(self):
        if self.modified_on is None:
            return self.created_on
        return self.modified_on

    def get_absolute_url(self):
        return reverse('website:account_update', kwargs={'pk': self.pk})

    def __str__(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)


class CommonEntity(models.Model):
    created_by = models.ForeignKey(
        DjangoUser, related_name="%(app_label)s_%(class)s_add"
    )
    created_on = models.DateTimeField(
        verbose_name=u"Created on", auto_now_add=True
    )
    modified_by = models.ForeignKey(
        DjangoUser, related_name="%(app_label)s_%(class)s_update",
        null=True, blank=True
    )
    modified_on = models.DateTimeField(
        verbose_name=u"Updated on", auto_now=True, null=True, blank=True
    )

    class Meta:
        abstract = True


class UserFollow(models.Model):
    followed_on = models.DateTimeField(
        verbose_name=u"Segui dal", auto_now_add=True
    )
    user_following = models.ForeignKey(
        UserProfile, verbose_name=u"Seguito da",
        related_name="%(app_label)s_%(class)s_following",
    )
    user_followed = models.ForeignKey(
        UserProfile, verbose_name=u"Segue",
        related_name="%(app_label)s_%(class)s_followed",
    )

    class Meta:
        unique_together = ('user_following', 'user_followed')

    def __str__(self):
        return "following: %s / followed:%s" % (
            self.user_following, self.user_followed
        )


class ContentCategory(ReferenceEntity):
    # Ciecita, ipovisione, Sordita...

    icon = models.ImageField(upload_to='content_category/icons')

    class Meta:
        verbose_name = u"Categoria di contenuto"
        verbose_name_plural = u"Categorie di contenuto"
        ordering = ['label']


class ContentBaseQuerySet(models.QuerySet):
    def search(self, search_text):
        return self.filter(
            Q(title__icontains=search_text.lower()) |
            Q(text__icontains=search_text.lower())
        )


class ContentBase(models.Model):
    title = models.CharField(u"Titolo", max_length=120)
    text = models.TextField(u"Descrizione")

    user_created_by = models.ForeignKey(
        UserProfile, related_name="%(app_label)s_%(class)s_add"
    )
    user_created_on = models.DateTimeField(
        verbose_name=u"Created on", auto_now_add=True
    )
    user_modified_by = models.ForeignKey(
        UserProfile, related_name="%(app_label)s_%(class)s_update",
        null=True, blank=True
    )
    user_modified_on = models.DateTimeField(
        verbose_name=u"Updated on", auto_now=True, null=True, blank=True
    )

    class Meta:
        abstract = True

    def last_modified(self):
        if self.user_modified_on is None:
            return self.user_created_on
        return self.user_modified_on
    
    def full_title(self):
        return self.title

    def __str__(self):
        return self.title


class ContentQuerySet(ContentBaseQuerySet):
    def list_posts(self):
        return self.filter(content_type='post')

    def list_events(self):
        return self.filter(content_type='event')

    def list_tutorials(self):
        return self.filter(content_type='tutorial')

    def list_by_category(self, cc_id):
        return self.filter(category=cc_id)

    def list_no_category(self):
        return self.filter(category__isnull=True)

    def list_liked_by(self, user_profile_id):
        # Get all ids of users that are following
        # the current UserProfile instance
        contents_ids = (
            ContentLike.objects
            .filter(user_profile__id=user_profile_id)
            .values_list('content', flat=True)
        )

templates/website/account/account_created.html
{% extends 'website/skeletons/tpl_general_message.html' %}
{% block title_general_msg %}
    Registrazione completa!<br>
{% endblock %}
{% block content_general_msg %}
    <a id="loginLink" href="{% url 'website:login' %}">Clicca qui</a> per fare il login
{% endblock %}

templates/website/account/account_edit.html
{% extends 'website/skeletons/tpl_base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}Infinity Access{% endblock %}

{% block content %}

<div id="accountEditPage" class="row">
    <div class="col-md-offset-6 col-md-4 col-xs-offset-2 col-xs-12 profile-form">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">{% if up_form.instance.id %}Modifica account{% else %}Registrazione ({{ step }} / 2){% endif %}</h3>
            </div>
            <div class="panel-body">
                <form id="profile_form" method="post" enctype="multipart/form-data" action="">{% csrf_token %}
                    <div class="form-group">
                        {% if up_form.errors or user_form.errors %}
                            <div id="formErrors" class="row">
                                <p class="global-error">Ci sono errori:</p>
                            </div>
                        {% endif %}
                        {% if step == "1" %}
                            <div class="row">
                                {{ user_form.first_name.errors }}
                                <label for="{{ user_form.first_name.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ user_form.first_name.css_classes }}">{{ user_form.first_name.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ user_form.first_name }}
                                </div>
                            </div>
                            <div class="row">
                                {{ user_form.last_name.errors }}
                                <label for="{{ user_form.email.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ user_form.last_name.css_classes }}">{{ user_form.last_name.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ user_form.last_name }}
                                </div>
                            </div>
                            <div class="row">
                                {{ user_form.email.errors }}
                                <label for="{{ user_form.email.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ user_form.email.css_classes }}">{{ user_form.email.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ user_form.email }}
                                </div>
                            </div>
                            <div class="row">
                                {{ user_form.password1.errors }}
                                <label for="{{ user_form.password1.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ user_form.password1.css_classes }}">{{ user_form.password1.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ user_form.password1 }}
                                </div>
                            </div>
                            <div class="row">
                                {{ user_form.password2.errors }}
                                <label for="{{ user_form.password2.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ user_form.password2.css_classes }}">{{ user_form.password2.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ user_form.password2 }}
                                </div>
                            </div>
                            <!--begin-->
                            <div class="row">
                                {{ up_form.city.errors }}
                                <label for="{{ up_form.city.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.city.css_classes }}">{{ up_form.city.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.city }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.place_interest_1.errors }}
                                <label for="{{ up_form.place_interest_1.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.place_interest_1.css_classes }}">{{ up_form.place_interest_1.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.place_interest_1 }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.place_interest_2.errors }}
                                <label for="{{ up_form.place_interest_2.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.place_interest_2.css_classes }}">{{ up_form.place_interest_2.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.place_interest_2 }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.country.errors }}
                                <label for="{{ up_form.country.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.country.css_classes }}">{{ up_form.country.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.country }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.sex.errors }}
                                <label for="{{ up_form.sex.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.sex.css_classes }}">{{ up_form.sex.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.sex }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.age.errors }}
                                <label for="{{ up_form.age.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.age.css_classes }}">{{ up_form.age.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.age }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.web_site.errors }}
                                <label for="{{ up_form.web_site.id_for_label }}" class="col-md-6 col-sm-6 control-label {{ up_form.web_site.css_classes }}">{{ up_form.web_site.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.web_site }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.information.errors }}
                                <label for="{{ up_form.information.id_for_label }}" class="control-label {{ up_form.information.css_classes }}">{{ up_form.information.label }}</label>
                                <div class="col-md-16 col-sm-9">
                                    {{ up_form.information }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.newsletter_registered.errors }}
                                
                                <div class="col-md-16 col-sm-9 checkboxes">
                                    {{ up_form.newsletter_registered }}
                                    <label for="{{ up_form.newsletter_registered.id_for_label }}" class="control-label {{ up_form.newsletter_registered.css_classes }}">{{ up_form.newsletter_registered.label }}</label>
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.mail_post_liked.errors }}

                                <div class="col-md-16 col-sm-9 checkboxes">
                                    {{ up_form.mail_post_liked }}
                                    <label for="{{ up_form.mail_post_liked.id_for_label }}" class="control-label {{ up_form.mail_post_liked.css_classes }}">{{ up_form.mail_post_liked.label }}</label>
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.mail_followed.errors }}

                                <div class="col-md-16 col-sm-9 checkboxes">
                                    {{ up_form.mail_followed }}
                                <label for="{{ up_form.mail_followed.id_for_label }}" class="control-label {{ up_form.mail_followed.css_classes }}">{{ up_form.mail_followed.label }}</label>                               
                                </div>

                            </div>
                            <div class="row">
                                {{ up_form.mail_comment.errors }}
                                <div class="col-md-16 col-sm-9 checkboxes">
                                    {{ up_form.mail_comment }}
                                    <label for="{{ up_form.mail_comment.id_for_label }}" class="control-label {{ up_form.mail_comment.css_classes }}">{{ up_form.mail_comment.label }}</label>
                                </div>
                            </div><!--end of begin-->
                        {% endif %}
                        {% if step == "2" %}
                            {{ up_form.category.errors }}
                            <div class="row user-category-list">
                                {{ up_form.category.as_hidden }}
                                <ul>
                                    {% for uc in user_category_list %}
                                        <li onclick="selectUserCategory({{ uc.id }});" id="category-{{ uc.id }}">&nbsp;{{ uc.label }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="row">
                                {{ up_form.avatar.errors }}
                                <label for="{{ up_form.avatar.id_for_label }}" class="col-md-3 control-label {{ up_form.avatar.css_classes }}">{{ up_form.avatar.label }}</label>
                                <div class="col-md-9">
                                    {{ up_form.avatar }}
                                </div>
                            </div>
                            <div class="row">
                                {{ up_form.terms_and_conditions.errors }}
                                <div class="col-md-16 col-sm-9 checkboxes">
                                    {{ up_form.terms_and_conditions }}
                                    <label for="{{ up_form.terms_and_conditions.id_for_label }}" class="control-label {{ up_form.terms_and_conditions.css_classes }}">{{ up_form.terms_and_conditions.label }}</label>
                                </div>
                            </div>
                        {% endif %}

                    </div> <!-- end form-group -->
                    <!-- TODO: check col / col-offset are right -->
                    <div class="form-group">
                        <div class="col-md-offset-7 col-md-2 col-sm-16 col-xs-offset-13 col-xs-2">
                            <button id="submitButton" type="submit" class="btn btn-primary submit-btn">
                                {% if step == "1" %}
                                    Avanti
                                {% elif step == "2" %}
                                    {% if up_form.instance.id %}Modifica account{% else %}Registrati{% endif %}
                                {% endif %}
                            </button>
                        </div>
                    </div>
                    {% if up_form.instance.id %}
                    <div class="form-group">
                        <div id="lastUpdatedText" class="col-md-offset-3 col-md-11 col-sm-offset-3 col-sm-11 col-xs-offset-2 col-xs-11 form-footer">
                            Ultima modifica: {{ up_form.instance.modified_on|date:"d/m/Y - H:i" }}
                        </div>
                    </div>
                    {% endif %}
                </form>
            </div><!-- end panel-body-->
        </div><!-- end panel -->
    </div><!-- /.col-sm-12 -->
</div>



{% endblock %}

{% block jscript %}
<script>
$(function() {
    // Eventually select the category when it was previously selected
    category_id = $('#id_category').val()
    if (category_id != '') {
        $('#category-'+category_id).attr('class', 'category-selected');
    }
});
function selectUserCategory(category_id) {
    // Unselect all categories
    $( "[id^=category-]" ).each(function( index ) {
        $('#'+this.id).attr('class', '');
    });
    // Select the one clicked on
    $('#category-'+category_id).attr('class', 'category-selected');
    $('#id_category').val(category_id); // id_category is generated by up_form.category.as_hidden
}
</script>
{% endblock %}

templates/website/account/login.html
{% extends 'website/skeletons/tpl_base.html' %}

{% block title %}Login{% endblock %}

{% block pageTitle %}Login{% endblock %}

{% block content %}

<div id="loginPage" class="row">
    <div class="col-md-offset-6 col-md-4 col-sm-6 col-xs-offset-3 col-xs-10 simple-form">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title">Login</h2>
            </div>
            <div class="panel-body">
                <form id="login_form" method="post" action="{% url 'website:login' %}">{% csrf_token %}
                    {% if messages %}
                    <ul id="msgLst" class="messages global-error">
                        {% for message in messages %}
                        <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <div class="form-group">
                        <div class="row">
                            <label for="username" class="col-md-6 col-sm-6 control-label">Indirizzo email</label>
                            <div class="col-md-16 col-sm-16">
                                <input id="username" type="text" name="username" value="" size="45" />
                            </div>
                        </div>
                        <div class="row">
                            <label for="password" class="col-md-6 col-sm-6 control-label">Password</label>
                            <div class="col-md-16 col-sm-16">
                                <input id="password" type="password" name="password" value="" size="45" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-16 col-sm-16 dimenticato" align="left">
                                <p>Hai dimenticato la password? <a href="{% url 'website:reset_password_request' 'init' %}">Clicca qui</a> per reimpostarla.</p>
                            </div>
                        </div>
                    </div>        
                    <div class="form-group">
                        <div class="col-md-offset-7 col-md-2 col-xs-offset-13 col-xs-2">
                            <button id="loginButton" type="submit" class="btn btn-primary submit-btn">Accedi</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}